apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-server
  namespace: cloud
  labels:
    app: proxy-server
spec:
  selector:
    matchLabels:
      app: proxy-server-pod
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: proxy-server-pod
    spec:
      containers:
      - name: proxy-server
        image: nginx:1.18.0-alpine
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi
        ports:
          - containerPort: 80
          - containerPort: 443
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
          readOnly: true
        - name: nginx-ssl-volume
          mountPath: /etc/nginx/ssl/live/
          readOnly: true
      volumes:
        - name: nginx-config-volume
          configMap:
            name: voting-app-config-map
            items:
            - key: default.conf
              path: default.conf
        - name: nginx-ssl-volume
          configMap:
            name: voting-app-config-map
            items:
            - key: self-signed-ssl.crt
              path: self-signed-ssl.crt
            - key: self-signed-ssl.key
              path: self-signed-ssl.key
      restartPolicy: Always