apiVersion: apps/v1
kind: Deployment
metadata:
  name:  redis-db
  namespace: cloud
  labels:
    app:  redis-db
spec:
  selector:
    matchLabels:
      app: redis-db-pod
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  redis-db-pod
    spec:
      containers:
      - name:  redis-db
        image:  redis:7.0-alpine3.15
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi
        ports:
        - containerPort: 6379
          name:  redis-db
      restartPolicy: Always