apiVersion: v1
kind: Pod
metadata:
  name: seeder-app
  namespace: cloud
  labels:
    app: seeder-app
# spec:
#   selector:
#     matchLabels:
#       app: seeder-app-pod
#   replicas: 1
#   strategy:
#     rollingUpdate:
#       maxSurge: 25%
#       maxUnavailable: 25%
#     type: RollingUpdate
#   template:
#     metadata:
#       labels:
#         app: seeder-app-pod
spec:
  imagePullSecrets:
  - name: ecr-credentials
  containers:
  - name: seeder-app
    image: 966437228244.dkr.ecr.ap-southeast-1.amazonaws.com/seeder:1.0
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 512Mi
  restartPolicy: Never