apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-app
  namespace: cloud
  labels:
    app: vote-app
spec:
  selector:
    matchLabels:
      app: vote-app-pod
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: vote-app-pod
    spec:
      imagePullSecrets:
      - name: ecr-credentials
      containers:
      - name:  vote-app
        image:  966437228244.dkr.ecr.ap-southeast-1.amazonaws.com/vote:1.0
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi
        ports:
        - containerPort: 5000
      restartPolicy: Always