apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app
  namespace: cloud
  labels:
    app: worker-app
spec:
  selector:
    matchLabels:
      app: worker-app-pod
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: worker-app-pod
    spec:
      imagePullSecrets:
      - name: ecr-credentials
      containers:
      - name: worker-app
        image: 966437228244.dkr.ecr.ap-southeast-1.amazonaws.com/worker:1.0
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi
      restartPolicy: Always