apiVersion: v1
kind: ConfigMap
metadata:
  name: voting-app-config-map
  namespace: cloud
data:
  postgres_user: postgres
  self-signed-ssl.crt: |
    -----BEGIN CERTIFICATE-----
    MIID7zCCAtegAwIBAgIUfJE3IrgXUKeNbjOVeOT7FXnLykcwDQYJKoZIhvcNAQEL
    BQAwgYYxCzAJBgNVBAYTAlBIMQwwCgYDVQQIDANOQ1IxGTAXBgNVBAcMEE1hbmRh
    bHV5b25nIENpdHkxEzARBgNVBAoMClN0cmF0cG9pbnQxFTATBgNVBAsMDENsb3Vk
    LU5hdGl2ZTEiMCAGA1UEAwwZdm90ZS1hcHAuc3RyYXRwb2ludC5sb2NhbDAeFw0y
    MjA1MDkwMjQxMjVaFw0yMzA1MDkwMjQxMjVaMIGGMQswCQYDVQQGEwJQSDEMMAoG
    A1UECAwDTkNSMRkwFwYDVQQHDBBNYW5kYWx1eW9uZyBDaXR5MRMwEQYDVQQKDApT
    dHJhdHBvaW50MRUwEwYDVQQLDAxDbG91ZC1OYXRpdmUxIjAgBgNVBAMMGXZvdGUt
    YXBwLnN0cmF0cG9pbnQubG9jYWwwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
    AoIBAQCeSmGjTL2vLlTtssJaDHzOnmeop+ysZE2gux0Bodhk+D5G/GbHXvROAd1b
    ijIJnzzm8woODHaND1CfLeZpeqym1vxcYzzLqREbgP4deH/v2Fm50t7pPRYPng6e
    /K9H+ahSmqWU84APguvOgRfE+Z/1xE3RP25yI2vUf+DPvZTL1nGkxCZ6xFeqxpl8
    YuKBrhLBHSM8lRLorEA2DpUGh6q8HeOcrBVMIDLrqt/XTWDUATaHIEx7Phiu9YGN
    PkFKvqAJ546pAocqfEki/LphYPs5ry6MLQTj4M+kdUuQGhhuVOEPd6bBZE4sXY/3
    tiZO+7U09CTYncw9T9Zl+oS9g663AgMBAAGjUzBRMB0GA1UdDgQWBBTMLtnofoxE
    ux+x6+DfjGgLWH+MNzAfBgNVHSMEGDAWgBTMLtnofoxEux+x6+DfjGgLWH+MNzAP
    BgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQCLbv4DXK5C2XnADMmR
    19jUlfFdY6scUEgGFCmAKcwU/wwFU3hNiqaCRbH2cP06cMliA7phZpacpsWYnHJO
    iYBQmhJYhIM8RMkerM+qFnC1mlHR6UVzP62RlOMIddOo8H3ByWAeRIFmf44+p78Z
    bPl3/08DHomcm3TwVz28etUYFWBuw9AggF5BTQpNOpUn+/kOedx4unlbDYGkxERk
    eJDqR+XDK7Zz3GR7TnfMDODZ2sq6aBCCQkgXvieNFPWsM9bo0eiOzOsY4EnYSKEv
    DdQzpXSsYrbadq9Cxien8tHybtfF544iyB2jEY0lEdpaXkfkbxohCbEWC3ol23X5
    sQdk
    -----END CERTIFICATE-----
  self-signed-ssl.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCeSmGjTL2vLlTt
    ssJaDHzOnmeop+ysZE2gux0Bodhk+D5G/GbHXvROAd1bijIJnzzm8woODHaND1Cf
    LeZpeqym1vxcYzzLqREbgP4deH/v2Fm50t7pPRYPng6e/K9H+ahSmqWU84APguvO
    gRfE+Z/1xE3RP25yI2vUf+DPvZTL1nGkxCZ6xFeqxpl8YuKBrhLBHSM8lRLorEA2
    DpUGh6q8HeOcrBVMIDLrqt/XTWDUATaHIEx7Phiu9YGNPkFKvqAJ546pAocqfEki
    /LphYPs5ry6MLQTj4M+kdUuQGhhuVOEPd6bBZE4sXY/3tiZO+7U09CTYncw9T9Zl
    +oS9g663AgMBAAECggEARYMMlZXhxshl62yRBNJvDJ1rkBkOSjZSEL+a4VidmtmZ
    H7s/t1Xvm0IeX1C04JzZNeKNC9ZVSWTsVrrlcHS61RmcAUZjMFyyco2XCoIcTMuJ
    u5zq3ypAQeN7MD5vCwCL9pqLFHpKRoWL4Ee4lHu6z0bBlZ5xdhYwCEWQCCqM6WY1
    +iBXGfqIr/xUvZ0VPem3ni/GIwAfOePHwiJTxrZum5fbx2SlmRUcypI63t7dCAVz
    MXA7cMAjF0NGwNq8qG1GD37XGKBFCvHtQQeosMr1CZWf4Y9EE1gNmouC29b7Zwln
    TE8NwwoyNr15XN2iNaICXSdwmc8AqOX39R2hKeu1YQKBgQDLUp822yHMKApyg/FW
    QMNx+IACqlWe4Xmq6HijJp63Hl+iU9t3uatxKfofpHJyD8kVB+auBMQWKBP1mWQc
    AWTDAx5y7pBn9UrZYkpy8G7hDWxSZ2EYdyyssedKkBFpGyispB6siQCbnY6lGDDQ
    SVZumgMgCt/AAQSwO4agvC0v2wKBgQDHTQAHQ4nmUx6Yqu76fXu/EDTo5ilfqIcA
    IjHgSetlGWXzTJUm7p7U5s8x1QzaSDxM/GbMUSgbAu2pYFK2teOkxGudrBO2bk8A
    gKTQfgrZjefC7LGvs5QR/PhFCQ4QcOkdfYsyxjZ2vTUsmsnoTI4c8rzOkXkSP90g
    ln7vkqPRVQKBgFouT0f5ccgnilq4gvaKyyVl3wFPo6JQx7IyYi+bFZKK+kf5gcJc
    q9oJkFMwkUJeFgYp9vsASii5pgCtBGYXiCWm4H6BqbMybPx2SCcq1UMkvQLfr4U2
    dq4ySjAcLly8GxJXyPMl4QskmvxG+n+nx5pO3Uv9BrkWuomgHVp1nGU5AoGBAMRO
    8w00mFs3WjbUf8pZ2Y8L/qG9O9mOXVNjWy9qgCO4DbTFpVCQ0AAzTLjv+tXzOvo1
    z2fHNLLOgpxIVZDEvnLoSnwnJ8+U/don3K/ExxkdbsCQdkDzqJDDVSRi0+ib3vJ+
    W6LqnHD+06aY3PIkngKjkhgCMHgqUbwsoOGH1jZ1AoGBAIUri4NtMuOr0ebbd30j
    9+eW33MUfzHuGsklZmOhTUJelJcH2I4RaJjyaSyDP3FyWg2cgOORh1hQqfdhQ5So
    W75QFweZez10TlEvWqiuM5UzRWJ2qp9od1vvoNtQcMymzfsrE2/UE7ToGFDKAi+9
    cSWSmjjCeVhsFc8nqhZXBqDl
    -----END PRIVATE KEY-----
  default.conf: |
    server {
      listen 80;
      listen [::]:80;
      location / {
          proxy_pass http://vote:5000;
          proxy_redirect   off;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Host $server_name;
          proxy_set_header X-Forwarded-Proto https;
      }
      location /results/ {
          proxy_pass http://result:5001;
          proxy_redirect   off;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Host $server_name;
          proxy_set_header X-Forwarded-Proto https;
      }
      error_page 500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }
    }
    server_tokens off;
