apiVersion: v1
kind: Service
metadata:
  name: proxy-server-svc
  namespace: cloud
spec:
  type: LoadBalancer
  selector:
    app: proxy-server-pod
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 443
    targetPort: 443
    name: https
